server:
  port: ${PORT:0}

grpc:
  port: ${GRPC_SERVER_PORT:8085}
  host: localhost

spring:
  application:
    name: grpc-server
  data:
    mongodb:
      uri: ${MONGO_DB_URI:mongodb://user:root@localhost:27017/card_db?authSource=admin}
      auto-index-creation: true
  cloud:
    kubernetes:
      enabled: true
      discovery:
        enabled: true
      config:
        enabled: false